apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: web
    component: front-end
spec:
  selector: 
    matchLabels: 
      app: web
      component: front-end
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
        component: front-end
    spec:
      containers: 
        - image: rezgarc/basic-web-app-client
          imagePullPolicy: Always
          name: client
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet: 
              path: /
              port: 3000
          env:
            - name: SERVER_URL
              value: http://server