apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: basic-web-app
  labels:
    app: web
    component: backend
spec:
  selector:
    matchLabels:
      app: web
      component: backend
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
        component: backend
    spec:
      containers:
        - image: rezgarc/basic-web-app-server
          imagePullPolicy: Always
          name: server
          ports:
            - containerPort: 3000