apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: web
    component: front-end
spec:
  containers:
    - image: cadro/basic-web-app-client
      name: client
      ports:
        - containerPort: 80