apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: web
    component: backend
spec:
  containers:
    - image: cadro/basic-web-app-server
      name: server
      ports:
        - containerPort: 3000