apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: ssd-monitor
spec:
  selector:
    matchLabels:
      app: web
      component: daemon
  template:
    metadata:
      labels:
        app: web
        component: daemon
    spec:
      nodeSelector: 
        disk: ssd
      containers:
        - name: main
          image: rezgarc/basic-web-app-daemon